name: procurement_lakehouse
version: '1.0.0'
config-version: 2
profile: procurement_lakehouse
model-paths: ['models']
snapshot-paths: ['snapshots']
test-paths: ['tests']
models:
  procurement_lakehouse:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
    quality:
      +schema: audit
      +materialized: table
