procurement_lakehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'procurement') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'procurement') }}"
      port: "{{ env_var('POSTGRES_PORT', 5434) | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'procurement') }}"
      schema: marts
      threads: 4
